services:
  flask-single:
    # image: flask-single
    # mem_limit: 512m        # Maximum memory limit. Or, 512MB # Can use MB, GB, KB
    # mem_reservation: 256m  # Memory reservation (soft limit)
    # cpus: 0.5             # Maximum CPU limit (50% of one CPU)
  
    build:
      context: .
      dockerfile: Dockerfile.single
      tags:
        - "flask-single"
    container_name: flask-single
    ports:
      - "5001:5000"
    environment:
      - APP_ENV=production
      - PORT=5000
    # volumes:
    #   - ./app.py:/app/app.py:ro   # Mount local app.py into container (read-only)

  flask-multi:
    build:
      context: .
      dockerfile: Dockerfile.multi
      tags:
        - "flask-multi"
    container_name: flask-multi
    ports:
      - "5002:5000"
    environment:
      - APP_ENV=production
      - PORT=5000
    # volumes:
    #   - ./app.py:/app/app.py:ro   # Mount local app.py into container (read-only)
